# Generated by Django 3.0.7 on 2020-06-07 21:37

from django.db import migrations, models
import django.db.models.deletion
import ingredients.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredienttype',
            old_name='type_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredientunit',
            old_name='unit_text',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='conservation_time',
            field=models.DurationField(validators=[ingredients.models.validate_conservation_not_negative]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.IngredientType'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.IngredientUnit'),
        ),
    ]
