# Generated by Django 3.0.7 on 2020-06-09 11:47

from django.db import migrations, models
import ingredients.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20200607_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pub_date',
            field=models.DateTimeField(default=ingredients.models.get_pub_date, verbose_name='date published'),
        ),
    ]
