# Generated by Django 3.0.7 on 2020-06-09 13:58

from django.db import migrations, models
import ingredients.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20200609_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='conservation_day',
            field=models.IntegerField(validators=[ingredients.models.validate_conservation_not_negative]),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='conservation_time',
        )
    ]
